### ISSUE TITLE
colorway contrast makes key combination contents hard to read

### ISSUE THREAD

**Issue by crawfxrd** [qmk/qmk_configurator#271]
When using e.g. the Space Cadet colorway, the contrast for Quantum "Mod key combinations" makes it very hard to read.

This is what I see:
```css
.gmk-space-cadet-key {
    color: #e1dbd1;
}
.key-contents {
    background: #fff;
}
```

![qmk_configurator_contrast](https://user-images.githubusercontent.com/5222085/54062653-5c117c00-41d5-11e9-9bea-886a25a2db98.png)
